<a href="https://colab.research.google.com/github/JaeKyunKo/Engineering_Department_Tutoring/blob/main/Tutoring_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy (Python Library)**

List (Python Data Structure)

In [1]:
#List Declaration
lstOne, lstTwo = list(), list()

In [2]:
for i in range(5) :
  lstOne.append(i)
  lstTwo.append(i+1)

In [4]:
print(lstOne, lstTwo)

[0, 1, 2, 3, 4] [1, 2, 3, 4, 5]


In [6]:
lstNew = lstOne + lstTwo

In [7]:
len(lstNew)

10

**Import Numpy Libraray**

In [8]:
import numpy as np

**Numpy Array Declaration**

np.array(list_name, data_type)

data_type -> int / float / str / ...

In [20]:
arrayExample = np.array([1,2])

In [40]:
arrayOne = np.array(lstOne, float)
arrayTwo = np.array(lstTwo, int)

In [41]:
for i in range(5) :
  print(type(arrayOne[i]))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [42]:
print(arrayOne, arrayTwo)
print(type(lstOne), type(lstTwo))
print(type(arrayOne), type(arrayTwo))

[0. 1. 2. 3. 4.] [1 2 3 4 5]
<class 'list'> <class 'list'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


Index Addition Implementation

In [43]:
arrayNew = arrayOne + arrayTwo

In [44]:
print(arrayNew)

[1. 3. 5. 7. 9.]


Same Implementation with Python list

In [18]:
for i in range(5) :
  arrayNew[i] = arrayOne[i] + arrayTwo[i]

In [19]:
print(arrayNew)

[1 3 5 7 9]


**2D or N-Dimensional Array Declaration**

In [23]:
array2D = np.array([[1,2,3], [4,5,6]])

In [24]:
print(array2D)

[[1 2 3]
 [4 5 6]]


**Finding Array Size(Shape)**

In [45]:
n, m = np.shape(array2D)

In [48]:
print(n, m)

2 3


**Initializing Array Size**

Python -> Declaration + Initialization 

Therefore, cannot set the size of array before Initialization

In [50]:
n, m = 3, 3
arrayInit = np.zeros((n,m))

In [51]:
print(arrayInit)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [53]:
arrayInit = np.ones((n,m))
print(arrayInit)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [54]:
numFull = 255
arrayInit = np.full((n,m), numFull)
print(arrayInit)

[[255 255 255]
 [255 255 255]
 [255 255 255]]


In [55]:
unitMatrix = np.eye(3)
print(unitMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [72]:
startPoint = 0
endPoint = 10
stepSize = 1
np.arange(startPoint ,endPoint ,stepSize)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
divisionSize = 10
np.linspace(startPoint, endPoint, divisionSize)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [75]:
np.random.random((2,2))

array([[0.90007617, 0.36435282],
       [0.48766634, 0.93217602]])

In [76]:
arrayEmpty = np.empty((3,3))

In [79]:
print(arrayEmpty)

[[ 1.11111111  2.22222222  3.33333333]
 [ 4.44444444  5.55555556  6.66666667]
 [ 7.77777778  8.88888889 10.        ]]


**Data Types in Numpy**

In [80]:
np.int

int

In [81]:
np.float

float

In [82]:
np.complex

complex

In [83]:
np.bool

bool

In [84]:
np.string_

numpy.bytes_

**Numpy Array Indexing and Slicing**